version: "3.1"
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=splitter"
      - "POSTGRES_USER=theuser"
      - "POSTGRES_PASSWORD=thepassword"