version: "3.1"
services:
  database:
    image: postgres:15-alpine
    ports:
      - "4321:4321"
    environment:
      - "POSTGRES_DB=Splitter"
      - "POSTGRES_USER=theuser"
      - "POSTGRES_PASSWORD=thepassword"