logging:
  level:
    org:
      springframework:
        security: info
    level:
      root: warn

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/splitter
    username: theuser
    password: thepassword
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo



