logging:
  level:
    org:
      springframework:
        security: info

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

flyway:
  schemas: Splitter
  create-schemas: true
  url: jdbc:postgresql://localhost:4321/Splitter
  user: theuser
  password: thepassword

  datasource:
    url: jdbc:postgresql://localhost:4321/Splitter
    username: theuser
    password: thepassword